# Generated by Django 4.2.7 on 2025-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=10, null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_key', models.BigIntegerField()),
                ('campaign', models.IntegerField()),
            ],
            options={
                'db_table': 'campaign_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CausalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('store_id', models.BigIntegerField()),
                ('week_no', models.IntegerField()),
                ('display', models.IntegerField()),
                ('mailer', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'causal_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_upc', models.CharField(max_length=20, unique=True)),
                ('product_id', models.BigIntegerField()),
                ('campaign', models.IntegerField()),
            ],
            options={
                'db_table': 'coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_key', models.BigIntegerField()),
                ('day', models.IntegerField()),
                ('coupon_upc', models.CharField(max_length=20)),
                ('campaign', models.IntegerField()),
            ],
            options={
                'db_table': 'coupon_redemption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DunnhumbyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(unique=True)),
                ('manufacturer', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('commodity_desc', models.CharField(max_length=100)),
                ('sub_commodity_desc', models.CharField(max_length=100)),
                ('curr_size_of_product', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_key', models.BigIntegerField(unique=True)),
                ('age_desc', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status_code', models.CharField(blank=True, max_length=5, null=True)),
                ('income_desc', models.CharField(blank=True, max_length=15, null=True)),
                ('homeowner_desc', models.CharField(blank=True, max_length=20, null=True)),
                ('hh_comp_desc', models.CharField(blank=True, max_length=30, null=True)),
                ('household_size_desc', models.CharField(blank=True, max_length=5, null=True)),
                ('kid_category_desc', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'household',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_key', models.BigIntegerField()),
                ('basket_id', models.BigIntegerField()),
                ('day', models.IntegerField()),
                ('product_id', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store_id', models.BigIntegerField()),
                ('retail_disc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_disc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_match_disc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_no', models.IntegerField()),
                ('trans_time', models.IntegerField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_key', models.BigIntegerField(unique=True)),
                ('recency_score', models.IntegerField()),
                ('frequency_score', models.IntegerField()),
                ('monetary_score', models.IntegerField()),
                ('rfm_segment', models.CharField(max_length=20)),
                ('last_transaction_day', models.IntegerField()),
                ('total_transactions', models.IntegerField()),
                ('total_spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_basket_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['rfm_segment'], name='dunnhumby_c_rfm_seg_17b9d3_idx'), models.Index(fields=['recency_score', 'frequency_score', 'monetary_score'], name='dunnhumby_c_recency_ae81c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BasketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.BigIntegerField()),
                ('household_key', models.BigIntegerField()),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('total_items', models.IntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department_mix', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['household_key'], name='dunnhumby_b_househo_571753_idx'), models.Index(fields=['basket_id'], name='dunnhumby_b_basket__a65eaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssociationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.JSONField()),
                ('consequent', models.JSONField()),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
                ('rule_type', models.CharField(choices=[('product', 'Product Level'), ('category', 'Category Level'), ('department', 'Department Level')], max_length=20)),
                ('min_support_threshold', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['support'], name='dunnhumby_a_support_853ef1_idx'), models.Index(fields=['confidence'], name='dunnhumby_a_confide_679d71_idx'), models.Index(fields=['lift'], name='dunnhumby_a_lift_a99612_idx'), models.Index(fields=['rule_type'], name='dunnhumby_a_rule_ty_c2743d_idx')],
            },
        ),
    ]
